export const browserCoreExamples = [
  "nova-ai browser status",
  "nova-ai browser start",
  "nova-ai browser start --headless",
  "nova-ai browser stop",
  "nova-ai browser tabs",
  "nova-ai browser open https://example.com",
  "nova-ai browser focus abcd1234",
  "nova-ai browser close abcd1234",
  "nova-ai browser screenshot",
  "nova-ai browser screenshot --full-page",
  "nova-ai browser screenshot --ref 12",
  "nova-ai browser snapshot",
  "nova-ai browser snapshot --format aria --limit 200",
  "nova-ai browser snapshot --efficient",
  "nova-ai browser snapshot --labels",
];

export const browserActionExamples = [
  "nova-ai browser navigate https://example.com",
  "nova-ai browser resize 1280 720",
  "nova-ai browser click 12 --double",
  "nova-ai browser click-coords 120 340",
  'nova-ai browser type 23 "hello" --submit',
  "nova-ai browser press Enter",
  "nova-ai browser hover 44",
  "nova-ai browser drag 10 11",
  "nova-ai browser select 9 OptionA OptionB",
  "nova-ai browser upload /tmp/nova-ai/uploads/file.pdf",
  'nova-ai browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "nova-ai browser dialog --accept",
  'nova-ai browser wait --text "Done"',
  "nova-ai browser evaluate --fn '(el) => el.textContent' --ref 7",
  "nova-ai browser console --level error",
  "nova-ai browser pdf",
];
